# Generated by Django 5.0.7 on 2024-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
