# Generated by Django 5.0.7 on 2024-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_alter_message_room_alter_message_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="value",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
