# Generated by Django 5.0.7 on 2024-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_alter_message_room_alter_message_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="message",
            name="value",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=1000),
        ),
    ]
