# Generated by Django 5.0.7 on 2024-07-27 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_alter_message_date_alter_message_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000000),
        ),
    ]
